name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: rehosting-arc

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq xz-utils

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            max-jobs = 8
            cores = 8

      - name: Configure Cachix
        uses: cachix/cachix-action@v16
        with:
          name: rehosting-tools
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.event_name == 'pull_request' }}

      - name: Flake Check
        run: nix flake check .

      - name: Build Release Artifact
        run: nix build .#dist && cp result penguin-tools.tar.gz

      - uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          use_api: true

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.v-version }}
          release_name: Release ${{ steps.version.outputs.v-version }}
          body: Release ${{ steps.version.outputs.v-version }} @${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./penguin-tools.tar.gz
          asset_name: penguin-tools.tar.gz
          asset_content_type: application/gzip

      - name: Publish release
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
